{ mkDerivation, fetchFromGitHub, amazonka, amazonka-core, amazonka-route53, base
, lens, network, stdenv
}:
mkDerivation {
  pname = "set-dyn-ip";
  version = "0.1.0.0";
  src = fetchFromGitHub {
    owner = "jerith666";
    repo = "set-dyn-ip";
    rev = "19b48b5070031413ca1b9d61b637758b6035b40f";
    sha256 = "0zr6h0ar0lsz1dl8mp3pdcs1wdyn3s5xpiqya34lz0paw7ssf9fk";
  };
  isLibrary = false;
  isExecutable = true;
  executableHaskellDepends = [
    amazonka amazonka-core amazonka-route53 base lens network
  ];
  homepage = "http://matt.mchenryfamily.org";
  description = "reads an ip address as generated by client-ip-echo and sets it in Amazon AWS Route53";
  license = stdenv.lib.licenses.lgpl3;
}
