{ lib, mkDerivation, fetchFromGitHub, amazonka, amazonka-core, amazonka-route53, base
, lens, network
}:
mkDerivation {
  pname = "set-dyn-ip";
  version = "1.0.0.0";
  src = fetchFromGitHub {
    owner = "jerith666";
    repo = "set-dyn-ip";
    rev = "0879acbb2797a7c7822cab5d33e7a04a15000935";
    hash = "sha256-2KAP/xMzQ9YQzjwPHpKvPBjb9JDixeGSvKUQLCr4Q0g=";
  };
  isLibrary = false;
  isExecutable = true;
  executableHaskellDepends = [
    amazonka amazonka-core amazonka-route53 base lens network
  ];
  homepage = "http://matt.mchenryfamily.org";
  description = "reads an ip address as generated by client-ip-echo and sets it in Amazon AWS Route53";
  license = lib.licenses.lgpl3;
  maintainers = [ lib.maintainers.jerith666 ];
}
