{ mkDerivation, fetchFromGitHub, amazonka, amazonka-core, amazonka-route53, base
, lens, network, stdenv
}:
mkDerivation {
  pname = "set-dyn-ip";
  version = "0.1.1.3";
  src = fetchFromGitHub {
    owner = "jerith666";
    repo = "set-dyn-ip";
    rev = "997c22c692517811be7ed56a6f94120032caa8d2";
    sha256 = "07kgha0x7ffa8mhibf6sa2pr09l4dfhbr0n8xkngh9ylzyf55a5s";
  };
  isLibrary = false;
  isExecutable = true;
  executableHaskellDepends = [
    amazonka amazonka-core amazonka-route53 base lens network
  ];
  homepage = "http://matt.mchenryfamily.org";
  description = "reads an ip address as generated by client-ip-echo and sets it in Amazon AWS Route53";
  license = stdenv.lib.licenses.lgpl3;
  maintainers = [ stdenv.lib.maintainers.jerith666 ];
}
